#!groovy
// Run docker build
properties([disableConcurrentBuilds()])

pipeline {
    agent { 
        label 'master'
        }
    options {
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
        timestamps()
    }
    stages {
        stage("docker swarm leave") {
            steps {
                
                    sh 'docker swarm leave -f'
                    
                }
            }

        stage("docker container prune") {
            steps {
                
                    sh 'docker container prune'
                    
                }
            }

        stage("docker volume prune") {
            steps {
                
                    sh 'docker volume prune'
                    
                }
            }         
    
        stage("docker image prune") {
            steps {
                
                    sh 'docker image prune -f -a'
                    
                }
            }
    
    
    
    
    
    
    }
}    





