#!groovy
// Run docker build
properties([disableConcurrentBuilds()])

pipeline {
    agent { 
        label 'master'
        }
    options {
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
        timestamps()
    }
    stages {
        stage("docker-container stop & delete") {
            steps {
                
                    sh 'docker stop $(docker ps -a -q) && docker rm $(docker ps -a -q)'
                    
                }
            }
    
    
    
    
    
    
    
    
    }
}    





