#!groovy
// Run docker build
properties([disableConcurrentBuilds()])

pipeline {
    agent { 
        label 'master'
        }
    options {
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
        timestamps()
    }
    stages {
        stage("docker login") {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub_nortonts', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh """
                    docker login -u $USERNAME -p $PASSWORD 
                    """
                }
            }
        } 

        stage("swarm") {
            steps {
                sh 'docker swarm init'
                }
            }  

        stage("build docker-compose") {
            steps {
                dir ('Docker_swarm') {
                    sh 'docker-compose build'
                    }
                }
            }

        stage("run node") {
            steps {
                dir ('Docker_swarm') {
                sh 'docker stack deploy nodeapp -c docker-compose.yml'
                    }
                }     
            }    
    
    
    
    
    
    
    
    }
}              