#!groovy
// Run docker build
properties([disableConcurrentBuilds()])

pipeline {
    agent { 
        label 'master'
        }
    options {
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
        timestamps()
    }
    stages {
        stage("docker login") {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub_nortonts', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh """
                    docker login -u $USERNAME -p $PASSWORD 
                    """
                }
            }
        } 
        stage("create ubuntu docker image") {
            steps {
                echo " ============== start building image =================="
                dir ('ubuntu') {
                	sh 'docker build -t ubuntu_python. '
                }
            }
        }
        stage("docker push") {
            steps {
                echo " ============== start pushing image =================="
                sh '''
                docker push nortonts/ubuntu_python:latest
                '''
            }
        }
    
    
    
    
    
    
    
    
    }
}              