version: '3'
services:
    web:
        image: nortonts/nginx_conf:latest
        restart: always
        ports:
            - "9000:9000" 
    pgAdmin:
        restart: always
        image: dpage/pgadmin4
        ports:
            - "80:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: 1234@admin.com
            PGADMIN_DEFAULT_PASSWORD: 1234
        volumes:
            - pgadmin:/var/lib/pgadmin
    postgres:
        restart: always
        image: postgres
        container_name: "postgres_container"
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: me
            POSTGRES_PASSWORD: 1234
            POSTGRES_DB: testDb
        volumes:
            - pgvol:/var/lib/postgresql/data
volumes:
    pgvol:
    pgadmin:
        

